name: unikp
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_1
  - blas=1.0=openblas
  - bottleneck=1.3.7=py38hbda83bc_0
  - brotli-python=1.0.9=py38h313beb8_8
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.11.4=hca03da5_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=py38hca03da5_0
  - debugpy=1.6.7=py38h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - et_xmlfile=1.1.0=py38hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.13.1=py38hca03da5_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.1.2=py38h8c48613_0
  - icu=75.1=hfee45f7_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - ipykernel=6.29.5=py38hca03da5_0
  - ipython=8.12.2=py38hca03da5_0
  - jedi=0.19.1=py38hca03da5_0
  - jinja2=3.1.4=py38hca03da5_0
  - joblib=1.4.2=py38hca03da5_0
  - jupyter_client=8.6.0=py38hca03da5_0
  - jupyter_core=5.7.2=py38hca03da5_0
  - libabseil=20240116.2=cxx17_h00cdb27_1
  - libcxx=17.0.6=he5c5206_2
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.29=hea593b9_0
  - libprotobuf=4.25.3=hc39d83c_1
  - libsentencepiece=0.2.0=h1751965_3
  - libsodium=1.0.20=h897f8a9_0
  - libsqlite=3.50.4=h4237e3c_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=14.0.6=hc6e5704_0
  - markupsafe=2.1.3=py38h80987f9_0
  - matplotlib-inline=0.1.6=py38hca03da5_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py38hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py38hca03da5_0
  - networkx=3.1=py38hca03da5_0
  - numexpr=2.8.4=py38h79ee842_1
  - numpy=1.24.3=py38h1398885_0
  - numpy-base=1.24.3=py38h90707a3_0
  - openpyxl=3.1.5=py38h80987f9_0
  - openssl=3.5.1=h81ee809_0
  - pandas=2.0.3=py38h46d7db6_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.2=py38hca03da5_0
  - platformdirs=3.10.0=py38hca03da5_0
  - pooch=1.7.0=py38hca03da5_0
  - prompt-toolkit=3.0.43=py38hca03da5_0
  - psutil=5.9.0=py38h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py38hca03da5_1
  - pysocks=1.7.1=py38hca03da5_0
  - python=3.8.20=h7d35d02_2_cpython
  - python-dateutil=2.9.0post0=py38hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.8=8_cp38
  - pytorch=2.4.1=py3.8_0
  - pytz=2024.1=py38hca03da5_0
  - pyyaml=6.0.2=py38h80987f9_0
  - pyzmq=25.1.2=py38h313beb8_0
  - readline=8.2=h1a28f6b_0
  - scikit-learn=0.24.2=py38h9197a36_1
  - scipy=1.10.1=py38h9d039d2_1
  - sentencepiece=0.2.0=h150bfb4_3
  - sentencepiece-python=0.2.0=py38h4affff1_3
  - sentencepiece-spm=0.2.0=h1751965_3
  - setuptools=75.1.0=py38hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.50.4=hb5dd463_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.13.3=py38hca03da5_0
  - threadpoolctl=3.5.0=py38h33ce5c2_0
  - tk=8.6.13=h892fb3f_2
  - tornado=6.4.1=py38h80987f9_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=py38hca03da5_0
  - typing_extensions=4.11.0=py38hca03da5_0
  - urllib3=2.2.3=py38hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.44.0=py38hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zipp=3.20.2=py38hca03da5_0
  - zlib=1.3.1=h8359307_2
  - pip:
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - hf-xet==1.1.5
      - huggingface-hub==0.34.3
      - idna==3.10
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - matplotlib==3.7.5
      - packaging==25.0
      - pillow==10.4.0
      - pyparsing==3.1.4
      - rdkit==2024.3.5
      - regex==2024.11.6
      - requests==2.32.4
      - safetensors==0.5.3
      - seaborn==0.13.2
      - tokenizers==0.20.3
      - transformers==4.46.3
prefix: /opt/anaconda3/envs/unikp
